### ISSUE TITLE
Python3.8运行出错

### ISSUE THREAD

**Issue by Saved1387** [JogleLew/channel-helper-bot#28]
错误log

``` shell
root@privacy:~/bot/channel-helper-bot# python3 helper_main.py
2020-11-02 09:56:21 [Log] (log.py: 44 in __init__()):
Logger [channel_helper] Initialized.

2020-11-02 09:56:21 [main] (helper_main.py: 40 in <module>()):
Admin List: [privacy, privacy]

2020-11-02 09:56:22 [main] (helper_main.py: 122 in <module>()):
{'id': [privacy], 'first_name': '[privacy]', 'is_bot': True, 'username': '[privacy]', 'can_join_groups': True, 'can_read_all_group_messages': False, 'supports_inline_queries': False}

helper_main.py:126: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(bot=bot, request_kwargs={'read_timeout': 6, 'connect_timeout': 7}, use_context=False)
2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "start_cmd"...

2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "help_cmd"...

2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "cancel_cmd"...

2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "sql_cmd"...

2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "clean_cmd"...

2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "register_cmd"...

2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "option_cmd"...

2020-11-02 09:56:22 [main] (helper_main.py: 182 in <module>()):
Loading module "channel_msg"...

2020-11-02 09:56:22 [Exception] (log.py: 21 in log_except_hook()):
Traceback (most recent call last):
  File "helper_main.py", line 183, in <module>
    current_module = importlib.import_module("modules." + module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/bot/channel-helper-bot/modules/channel_msg.py", line 424, in <module>
    channel_post_filter = FilterChannelPost()
TypeError: Can't instantiate abstract class FilterChannelPost with abstract methods __call__
```

python-telegram-bot版本
``` shell
root@privacy:~/auto_start/channel-helper-bot# pip3 install python-telegram-bot
Requirement already satisfied: python-telegram-bot in /usr/local/lib/python3.8/dist-packages (13.0)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from python-telegram-bot) (3.1)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from python-telegram-bot) (2020.6.20)
Requirement already satisfied: decorator>=4.4.0 in /usr/local/lib/python3.8/dist-packages (from python-telegram-bot) (4.4.2)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.8/dist-packages (from python-telegram-bot) (6.1)
Requirement already satisfied: APScheduler==3.6.3 in /usr/local/lib/python3.8/dist-packages (from python-telegram-bot) (3.6.3)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python-telegram-bot) (50.3.0)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python-telegram-bot) (2020.1)
Requirement already satisfied: tzlocal>=1.2 in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python-telegram-bot) (2.1)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python-telegram-bot) (1.15.0)
```

**Comment by JogleLew** [comment]
换个旧版的 `python-telegram-bot` 试一下，不知道是不是 API 更新了

**Comment by Pentacene** [comment]
> 换个旧版的 `python-telegram-bot` 试一下，不知道是不是 API 更新了

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-13.0#refactoring-of-filters

**Comment by SakuraPie** [comment]
把./modules/channel_msg.py的第419行改为”class FilterChannelPost(MessageFilter):“即可。

**Comment by Pentacene** [comment]
> 把./modules/channel_msg.py的第419行改为”class FilterChannelPost(MessageFilter):“即可。

```from telegram.ext import MessageFilter```

**Comment by JogleLew** [comment]
感谢各位，已修改
