### ISSUE TITLE
python3.9+python-telegram-bot13.3下运行报错

### ISSUE THREAD

**Issue by tjsky** [JogleLew/channel-helper-bot#34]
```
root@173:~/bot# python3 helper_main.py
/usr/local/python3/lib/python3.9/site-packages/telegram/utils/promise.py:26: TelegramDeprecationWarning: telegram.utils.promise is deprecated. Please use telegram.ext.utils.promise instead.
  warnings.warn(
Traceback (most recent call last):
  File "/root/commentbot/helper_main.py", line 16, in <module>
    import messagequeue as mq
  File "/root/commentbot/messagequeue.py", line 34, in <module>
    from ninesix import Logger
ModuleNotFoundError: No module named 'ninesix'
```
技术能力有限，没看出来应该怎么解决。

**Comment by SakuraPie** [comment]
安装依赖：
pip3 install ninesix

**Comment by tjsky** [comment]
> 安装依赖：
> pip3 install ninesix

丢人了。。谢谢解答
